# Generated by Django 4.1.7 on 2023-03-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempuser',
            name='username',
        ),
    ]
