# Generated by Django 4.1.7 on 2023-03-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_business_address_ngo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
